# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestSet():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(821, 856)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("tester")
    self.driver.find_element(By.NAME, "password").send_keys("dummy123")
    self.driver.find_element(By.ID, "login").click()
  
  def test_logout(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(821, 856)
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
  def test_modifyviewrecipeloggedin(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(821, 856)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("tester123")
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("tester")
    self.driver.find_element(By.NAME, "password").send_keys("dummy123")
    self.driver.find_element(By.ID, "login").click()
    self.driver.find_element(By.LINK_TEXT, "Recipes").click()
    self.driver.find_element(By.LINK_TEXT, "View Recipe").click()
    self.driver.find_element(By.LINK_TEXT, "Recipes").click()
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
    self.driver.find_element(By.LINK_TEXT, "Update").click()
    self.driver.find_element(By.ID, "id_directions").click()
    self.driver.find_element(By.ID, "id_directions").click()
    element = self.driver.find_element(By.ID, "id_directions")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "id_directions").click()
    self.driver.find_element(By.ID, "id_directions").click()
    self.driver.find_element(By.ID, "id_directions").click()
    self.driver.find_element(By.ID, "id_directions").send_keys("selenium view/edit recipes test")
    self.driver.find_element(By.NAME, "Submit").click()
    self.driver.find_element(By.LINK_TEXT, "View Recipe").click()
    self.driver.find_element(By.LINK_TEXT, "Recipes").click()
    self.driver.find_element(By.LINK_TEXT, "New Recipe").click()
    self.driver.find_element(By.ID, "id_title").click()
    self.driver.find_element(By.ID, "id_title").send_keys("new recipe")
    self.driver.find_element(By.ID, "id_ingredients").send_keys("a new recipe")
    self.driver.find_element(By.ID, "id_directions").click()
    self.driver.find_element(By.ID, "id_directions").send_keys("a new recipe test")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > .btn-primary").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
  def test_modifyviewrecipesnologin(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(821, 856)
    self.driver.find_element(By.LINK_TEXT, "Recipes").click()
    self.driver.find_element(By.LINK_TEXT, "View Recipe").click()
    self.driver.find_element(By.LINK_TEXT, "Recipes").click()
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
    self.driver.find_element(By.LINK_TEXT, "Recipes").click()
    self.driver.find_element(By.LINK_TEXT, "Update").click()
    self.driver.find_element(By.LINK_TEXT, "Recipes").click()
    self.driver.find_element(By.LINK_TEXT, "New Recipe").click()
    self.driver.find_element(By.LINK_TEXT, "Recipes").click()
  
