# Generated by Django 4.2.7 on 2023-11-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Enter title of recipe.')),
                ('ingredients', models.TextField(help_text='Enter the ingredients.')),
                ('directions', models.TextField(help_text='Enter the directions.')),
            ],
        ),
    ]
